site_name: ゼロから学ぶ Python
site_description: ゼロから学ぶ Python
site_author: IDA Kenichiro
site_url: http://rinatz.github.io/python-book
repo_name: rinatz/python-book
repo_url: https://github.com/rinatz/python-book
copyright: Copyright &copy 2020 IDA Kenichiro

theme:
  name: material
  palette:
    scheme: preference
    primary: orange
    accent: blue
  font:
    text: Noto Sans
    code: Inconsolata
  language: ja
  logo: img/python.svg
  favicon: img/python.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - meta

nav:
  - ホーム: index.md
  - 1. Python を始める:
    - 1.1. インストール: ch01-01-installation.md
    - 1.2. Hello, World!: ch01-02-hello-world.md
  - 2. 基本仕様:
    - 2.1. 変数: ch02-01-variables.md
    - 2.2. 関数: ch02-02-functions.md
    - 2.3. コメント: ch02-03-comments.md
    - 2.4. 条件文: ch02-04-conditions.md
    - 2.5. ループ文: ch02-05-loops.md
    - 2.6. リスト内包表記: ch02-06-list-comprehensions.md
    - 2.7. ラムダ式: ch02-07-lambdas.md
  - 3. クラス:
    - 3.1. クラス: ch03-01-classes.md
    - 3.2. スコープ: ch03-02-scopes.md
    - 3.3. 特殊属性: ch03-03-special-attributes.md
    - 3.4. プロパティ: ch03-04-properties.md
  - 4. モジュールとパッケージ:
    - 4.1. モジュール: ch04-01-modules.md
    - 4.2. パッケージ: ch04-02-packages.md
    - 4.3. pip: ch04-03-pip.md
    - 4.4. venv: ch04-04-venv.md
    - 4.5. pipenv: ch04-05-pipenv.md
    - 4.6. poetry: ch04-06-poetry.md
    - 4.7. プロジェクト構成: ch04-07-project-structures.md
  - 5. ファイル操作:
    - 5.1. ファイル操作: ch05-01-files.md
    - 5.2. コンテキスト: ch05-02-contexts.md
    - 5.3. CSV: ch05-03-csv.md
    - 5.4. JSON: ch05-04-json.md
  - 6. 例外:
    - 6.1. 例外: ch06-01-exceptions.md
  - 7. ジェネレータ:
    - 7.1. ジェネレータ: ch07-01-generators.md
  - 8. テスト:
    - 8.1. doctest: ch08-01-doctest.md
    - 8.2. pytest: ch08-02-pytest.md
